pipeline {
    agent any
    
    stages {
        stage('Checkout du code') {
            steps {
                git 'https://github.com/Linahamza/jenkinsfile.git'
            }
        }
        stage('Installation des dépendances') {
            steps {
                sh 'docker-compose run --rm app composer install'
            }
        }
        stage('Tests') {
            steps {
                sh 'docker-compose run --rm app php artisan test'
            }
        }
        stage('Déploiement') {
            steps {
                sh 'docker-compose down' // Arrêter et supprimer les conteneurs existants
                sh 'docker-compose up -d --build' // Démarrer de nouveaux conteneurs
            }
        }
        stage('Vérification du déploiement') {
            steps {
                // Ajoutez des étapes de vérification après le déploiement
            }
        }
    }
    post {
        failure {
            // Actions à effectuer en cas d'échec du pipeline
            echo 'Le pipeline a échoué. Vérifiez les journaux pour plus de détails.'
        }
    }
}

